id: P1F266394
initial_creation_type: input
source_metadata:
  title: Vimalamitra
  language: bo
  description: 'Texts by and about the eighth-century paṇḍita and Dzogchen master
    Vimalamitra (dri med bshes gnyen), who is said to have attained the rainbow body:'
  volume:
    c17f40c3bb684d4395599c3846879854:
      title: Prayer to the Great Paṇḍita Vimalamitra
      parent: Prayers
created_at: '2022-03-01T02:27:05.808997'
last_modified_at: '2022-03-01T02:27:05.809000'
